Bbcode dsl
Sbread/Project_kotlin pull request #3
Opened 2023-01-30 04:25 UTC by Sbread

2023-01-30 13:29 UTC, FireF0xIl requested changes
В целом хорошо. Поправьте ошибку и прикрутите запись в файл результата

2023-01-30 13:29 UTC, FireF0xIl commented on src/main/kotlin/Main.kt
> +        i { "text" }
Кажется, что всё-таки конструкции вида `bbcobject { bbcobject {  } }` хочется запретить

2023-01-30 13:29 UTC, FireF0xIl commented on src/main/kotlin/BBCodeDsl/BBCList.kt
> +    items.add(BBCBaseElement().apply { content = builder.invoke(this) })
А почему бы не просто `builder(this)`?

2023-01-30 13:29 UTC, FireF0xIl commented on src/main/kotlin/BBCodeAPI/BBCListApi.kt
> +            items.forEach { append("* $it\n") }
Раз уж начали использовать `buildString `, то красивее писать в  `expression body`

2023-01-30 13:29 UTC, FireF0xIl commented on src/main/kotlin/BBCodeAPI/BBCListApi.kt
> +            items.forEach { append("* $it\n") }
Я смотрю, что почти везде делается `append(что-то).append("\n")`. Это можно упростить если сделать функцию расширение для `StringBuilder` в каком-нибудь утил файле.
P.S. также существует `StringBuilder.appendLine()`

2023-01-30 16:57 UTC, Sbread commented on src/main/kotlin/Main.kt
> +        i { "text" }
fixed

2023-01-30 16:57 UTC, Sbread commented on src/main/kotlin/BBCodeDsl/BBCList.kt
> +    items.add(BBCBaseElement().apply { content = builder.invoke(this) })
поправил

2023-01-30 16:58 UTC, Sbread commented on src/main/kotlin/BBCodeAPI/BBCListApi.kt
> +            items.forEach { append("* $it\n") }
действительно, поправил

2023-01-30 16:58 UTC, Sbread commented on src/main/kotlin/BBCodeAPI/BBCListApi.kt
> +            items.forEach { append("* $it\n") }
fixed

2023-01-30 16:59 UTC, Sbread commented
> В целом хорошо. Поправьте ошибку и прикрутите запись в файл результата

поправил + добавил запись в файл

2023-01-31 11:19 UTC, FireF0xIl approved these changes

2023-01-31 11:19 UTC, FireF0xIl commented on src/main/kotlin/BBCodeAPI/BBCObjectApi.kt
> +        File(name).writeText(toString())
К слову при таком подходе может вылететь ошибка I/O, которая никак не обрабатывается

2023-02-12 21:38 UTC, merged